### ISSUE TITLE
Restarted trial doesn't save without new trial details

### ISSUE THREAD

**Issue by alexisgarland** [johndeverall/BehaviourCoder#28]
restarted trial doesn't save without new trial details - it leaves details in there (date, detail fields) but considers them empty unless you type something new in there

**Comment by johndeverall** [comment]
@alexisgarland 
So the replication steps appear to be
1. Start a new trial
2. Enter in the trial fields (for example date and baby name)
3. Choose 'Restart analysis'. 
4. Run the trial again to the end of the video. 
5. Choose 'Save data'. 
6. The software will report the fields cannot be empty in the reporting bar at the bottom of the screen.

What is the expected behaviour? 

Do you want all the text fields to clear when 'Restart analysis' is selected, or do you want them to stay populated?

**Comment by alexisgarland** [comment]
The expectation is that the data in the text fields will be visually cleared when 'Restart analysis' is selected.
